misp:
  enabled: True
  url: "https://{MISP_URL}" # Update with local MISP URL
  api_key: "{APT_KEY}"      # Update with local MISP API key
  ssl: False                # Set to `true` to use SSL
  verifycert: False         # Set to `true` to verify MISP certificate (Use ONLY if both certs are issues from same trusted Root CA)
  accepts:
    - ip-dst
    - domain
    - url
    - hash
    - filename
    - email
  returns:
    - ip-dst
    - domain
    - url
    - hash
    - filename
    - email
  playbook_functions:
    - send_to_misp
    - get_misp_event_by_type
    - create_misp_event
    - enable_threat_feed
    - disable_threat_feed
