misp:
  enabled: True
  url: "https://misp.pisword-dev.local"
  api_key: "qEpGART6KisGULUm60qOYE4nbi9uZN9v8v9kbtm5"
  ssl: False
  verifycert: False
  accepts:
    - ip-dst
    - domain
    - url
    - hash
    - filename
    - email
  returns:
    - ip-dst
    - domain
    - url
    - hash
    - filename
    - email
  playbook_functions:
    - send_to_misp
    - get_misp_event_by_type
    - create_misp_event
    - enable_threat_feed
    - disable_threat_feed
