pfsense:
  enabled: True
  url: "PFSENSE_URL" # update with local pfSense API URL
  api_key: "API_KEY" # update with local pfSense API key
  ssl: False         # Set to `True` to enable SSL
  verifycert: False  # Set to `True` to verify pfSense Certificate
  accepts:
    - ip-dst
  returns:
    - ip-dst
    - ip-src
    - port-dst
    - port-src
    - timestamp
    - pfsense-firewall-rule
    - pfsense-firewall-rule-tracker
    - pfsense-firewall-log
    - pfsense-dhcp-log
    - pfsense-system-log
    - pfsense-config-history-log
    - pfsense-firewall-status
    - pfsense-interface
  playbook_functions:
    - add_firewall_rule
    - read_firewall_rule
    - delete_firewall_rule
    - get_firewall_rule_by_description
    - get_firewall_rule_by_ip
    - get_firewall_rule_by_port
    - get_firewall_rule_by_tracker
    - get_interfaces
    - get_tracker_by_firewall_rule
    - get_firewall_status
    - get_config_history_logs
    - get_firewall_logs
    - get_dhcp_logs
    - get_system_logs
    - get_config_history_logs
    - get_firewall_logs_by_daterange
    - is_in_network_range
    - is_ip_valid
    - epoch_to_datetime
    - datetime_to_epoch
